inp = input()
l = len(inp)

print("(* THIS FILE HAS BEEN GENERATED BY misc/generate_bytecode.py*)\n\n")
arr = "bytecode"

print(f"let static {arr} = (0:int<8>)^{l};;\n")
print("let load_code () =")

for i in range(l-1):
  print(f"  {arr}.({i}) <- {ord(inp[i])};")

print(f"  {arr}.({l-1}) <- {ord(inp[l-1])};;")
